### ISSUE TITLE
Prevent high cardinality for routes with variables

### ISSUE THREAD

**Issue by jpmeijers** [766b/chi-prometheus#9]
I have a route with variables as follows:

`router.HandleFunc("/circles/{z}/{x}/{y}", GetCirclesTile)`

The chi-prometheus middleware logs stats per unique combination of variables, rather than per pattern. This causes huge amounts of different metrics.

How can I change the behaviour to be per pattern and not per unique set of variables?

**Comment by jpmeijers** [comment]
Today I ran into this issue again. So happy when I saw someone else reported this issue, until I noticed it was me a year and a half ago :see_no_evil:

**Comment by 766b** [comment]
Sorry for monumental absence. There was an old merge request (merged as #3) regarding this issue. Hopefully this fixes your problem.
